---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation


- name: Cloning oh-my-zsh
  become: yes
  become_user: "{{ django_app_user }}"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: installation|success
  register: cloning


- name: Creating new ~/.zshrc
  become: yes
  become_user: "{{ django_app_user }}"
  template:
    src: .zshrc
    dest: ~/.zshrc
  when: cloning|success


- name: Set zsh as default shell
  user: name={{ django_app_user }} shell=/bin/zsh
